// Type declarations for @liquicode/jsonstor-leveldb
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// Documents are stored in a LevelDB store.

declare module '@liquicode/jsonstor-leveldb'
{

	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** Path to the folder holding the LevelDB store. It is created if it does not exist. */
		Path: string;
		/** The collection this storage reads and writes. One store holds as many collections as you name. */
		CollectionName: string;
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** Always `'jsonstor-leveldb'`. The name this adapter registers under. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-leveldb.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];

}
